export type Action =
  | "/lock"
  | "/unlock"
  | "/unlatch"
  | "/buzzer"
  | "/state"
  | "/user"
  | "/arrived"
  | "/doorbell"
  | "/arm/buzzer"
  | "/arm/unlatch"
  | "/pushnotifications/register"
