version: "3.9"
services:
  doorbellserver:
    image: oven/bun:latest
    ports:
      - "4278:4278"
    container_name: doorbellserver
    volumes:
      - ./:/home/bun/app:ro
      - ./db:/db
      - ./keys:/keys:ro
    command: ["run", "--watch", "./src/main.ts"]
    restart: unless-stopped
  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: always
    command: "tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_KEY}"
