version: "3.9"
services:
  doorbellserver:
    ports:
      - "4278:4278"
    container_name: doorbellserver
    build:
      context: .
      labels:
        com.centurylinklabs.watchtower.enable: "false"
    restart: always
  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: always
    command: "tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_KEY}"
