version: "3.9"
name: doorbellserver
services:
  doorbellserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4278:4278"
    volumes:
      - ./:/home/bun/app:ro
      - ./db:/db
      - ./keys:/keys:ro
    command: ["node", "/app/dist/main.js"]
    restart: unless-stopped
    env_file:
      - .env
    labels:
      - com.centurylinklabs.watchtower.enable=false
    devices:
      - /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0:/dev/buzzer
    stop_grace_period: 2s
  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: always
    command: "tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_KEY}"
