version: "3.9"
services:
  doorbellserver:
    ports:
      - "4278:4278"
    container_name: doorbellserver
    build:
      context: .
      labels:
        com.centurylinklabs.watchtower.enable: "false"
    depends_on:
      - remote-access
    restart: always
  nginx:
    image: nginx:latest
    restart: always
    container_name: nginx
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/snippets:/etc/nginx/snippets
      - ./nginx/sites:/etc/nginx/sites
    ports:
      - "443:443"
