version: "3.9"
services:
  doorbellserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4278:4278"
    container_name: doorbellserver
    volumes:
      - ./:/home/bun/app:ro
      - ./db:/db
      - ./keys:/keys:ro
    command: ["node", "/app/index.js"]
    restart: unless-stopped
  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: always
    command: "tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_KEY}"
