# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

update_fastlane

def delete_temp_keychain(name)
  delete_keychain(
    name: name
  ) if File.exist? File.expand_path("~/Library/Keychains/#{name}-db")
end

def create_temp_keychain(name, password)
  create_keychain(
    name: name,
    password: password,
    unlock: false,
    timeout: 0
  )
end

def ensure_temp_keychain(name, password)
  delete_temp_keychain(name)
  create_temp_keychain(name, password)
end

default_platform(:ios)

platform :ios do
  lane :beta do
    keychain_name = 'fastlane-certs'
    keychain_password = 'ccccccttbrljutrkfflnkdvildiblbgfdjigfdllutud'
    ensure_temp_keychain(keychain_name, keychain_password)

    api_key = app_store_connect_api_key(
      key_id: "973754ZHPB",
      issuer_id: "69a6de6f-90cd-47e3-e053-5b8c7c11a4d1",
      key_filepath: "./AuthKey_973754ZHPB.p8",
      duration: 1200,
      in_house: false,
    )

    match(
      type: 'appstore',
      app_identifier: ["de.343max.ourhome.Our-Home"],
      api_key: api_key,
      readonly: false,
      git_url: 'https://github.com/343max/ourhome-certs.git',
      keychain_name: keychain_name,
      keychain_password: keychain_password,
    )
    
    build_app(
      project: "Our Home.xcodeproj/",
      scheme: "Our Home"
    )

    upload_to_testflight(
      api_key: api_key,
      # skip_waiting_for_build_processing: true
    )

    delete_temp_keychain(keychain_name)
  end
end
