on: workflow_dispatch
name: "Deploy Testflight"
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: "build info"
        run: |
          echo "build number: ${{ github.run_number }}"
      - name: install cert repo ssh key
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.6"
      - name: writing AppStore API Key
        run: echo "${{ secrets.APP_STORE_API_KEY }}" | base64 -d > ios/AuthKey_973754ZHPB.p8
      - name: generating XCConfig
        run: echo \"BUILD_NUMBER = github.run_number\" > ios/Config.xcconfig
      - name: bundle install
        run: |
          cd ios
          bundle install
      - name: fastlane:testflight
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        run: |
          cd ios
          bundle exec fastlane beta
